config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :newsscrapers do
    resources :comments 
  end
  root to: 'pages#index'
  

end

app/models/ability.rb
class Ability

include CanCan::Ability
  def initialize(user)
  user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :update, Newsscraper do |news|
      news.user == user
    end
      can :destroy, Newsscraper do |news|
      news.user == user
    end
      can :update, Comment do |comment|
      comment.user == user
    end
      can :destroy, Comment do |comment|
      comment.user == user
    end
      can :create, Newsscraper
      can :create, Comment
      can :read, :all
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :newsscraper
end

app/models/newsscraper.rb
class Newsscraper < ActiveRecord::Base
    belongs_to :user
    has_many :comments
    
    validates :title_url, uniqueness: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :newsscrapers
  
  # has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, 
  # default_url: "nia.jpg" 
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  rescue_from CanCan::AccessDenied do |exception|
  redirect_to root_path
  flash[:alert] = "Sorry, you are not authorized to access this area!"
end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource param_method: :my_sanitizer
  load_and_authorize_resource :through => :current_user
  before_action :authenticate_user!

  # GET /comments/new
  def new
    @comment = Comment.new
  end


  # POST /comments
  # POST /comments.json
  def create
    @newsscraper = Newsscraper.find(params[:newsscraper_id])
    @comment = @newsscraper.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @newsscraper, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @comment.newsscraper, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:newsscraper_id, :body, :user_id)
    end
    
    def my_sanitizer
      params.require(:comment).permit(:body)
    end
end

app/controllers/newsscrapers_controller.rb
class NewsscrapersController < ApplicationController
  before_action :set_newsscraper, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /newsscrapers
  # GET /newsscrapers.json
  def index
    @newsscrapers = Newsscraper.all
    @newsscrapers = Newsscraper.paginate(page: params[:page], per_page: 10).order("created_at ASC")
  end

  # GET /newsscrapers/1
  # GET /newsscrapers/1.json
  def show
  end

  # GET /newsscrapers/new
  def new
    @newsscraper = Newsscraper.new
  end

  # GET /newsscrapers/1/edit
  def edit
     authorize! :update, @newsscraper
  end

  # POST /newsscrapers
  # POST /newsscrapers.json
  def create
    @newsscraper = Newsscraper.new(newsscraper_params)

    respond_to do |format|
      if @newsscraper.save
        format.html { redirect_to @newsscraper, notice: 'Newsscraper was successfully created.' }
        format.json { render :show, status: :created, location: @newsscraper }
      else
        format.html { render :new }
        format.json { render json: @newsscraper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsscrapers/1
  # PATCH/PUT /newsscrapers/1.json
  def update
    authorize! :update, @newsscraper
    respond_to do |format|
      if @newsscraper.update(newsscraper_params)
        format.html { redirect_to @newsscraper, notice: 'Newsscraper was successfully updated.' }
        format.json { render :show, status: :ok, location: @newsscraper }
      else
        format.html { render :edit }
        format.json { render json: @newsscraper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsscrapers/1
  # DELETE /newsscrapers/1.json
  def destroy
    authorize! :destroy, @newsscraper
    @newsscraper.destroy
    respond_to do |format|
      format.html { redirect_to newsscrapers_url, notice: 'Newsscraper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsscraper
      @newsscraper = Newsscraper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsscraper_params
      params.require(:newsscraper).permit(:title_url, :title, :body, :time, :image_url)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        @newsscrapers = Newsscraper.all.first(4)
        @comments = Comment.last(30)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private
        def sign_up_params
            params.require(:user).permit(
                :email,
                :password,
                :password_confirmation,
                :username,
                :image,
                :url
            )
        end
        
        def account_update_params
            params.require(:user).permit(
                :email,
                :password,
                :password_confirmation,
                :current_password,
                :username,
                :image,
                :url
            )
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/newsscrapers_helper.rb
module NewsscrapersHelper
end

app/views/comments/_comment.html.erb
<div class="col-md-12">
    <div class="caption-full">
        <h4 class="pull-right">Was posted <%= time_ago_in_words(comment.created_at) %> ago</h4>
        <h4>Comment By <%= comment.user.username %></h4>
        <%= image_tag comment.user.image.url(:thumb), class: "img-circle" %>
        <p><%= comment.body %></p>
        <% if can? :destroy, comment %>
            <%= link_to 'Destroy', [comment.newsscraper, comment], method: :delete,
            data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-xs" %>
        <% end %>
    </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for(@comment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :newsscraper_id %>
    <%= f.input :body %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Newsscraper</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.newsscraper_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Newsscraper:</strong>
  <%= @comment.newsscraper_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_alert.html.erb
<% if notice || alert %>
    <div class="alert <%= notice ? "alert-info" : "" %><%= alert ? "alert-danger" : "" %> alertdismissible"role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span><span class="sronly">Close</span>
        </button>
        <div >
            <% if notice %>
                <%= notice %>
            <% elsif alert %>
                <%= alert %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div class='container'>
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Your Website 2014</p>
            </div>
        </div>
        <!-- /.row -->
    </footer>
</div>  

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" datatarget="#bs-example-navbar-collapse-1"aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Newsscraper", root_path, class: "navbar-brand" %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
            <% if !current_user %>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
                <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>
            <li><%= link_to "Newsscraper", newsscrapers_path %></li>
            <% if current_user %>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" ariahaspopup="true" aria-expanded="false">
                <%= current_user.username %> <span class="caret"></span></a>
            <% end %>
            <ul class="dropdown-menu">
                <li><%= link_to "Edit my profile", edit_user_registration_path %></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "End my session", destroy_user_session_path, method: :delete %></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scraper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/alert' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<div class='container'>
  <%= yield %>
</div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/newsscrapers/_form.html.erb
<%= simple_form_for(@newsscraper) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title_url %>
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :time %>
    <%= f.input :image_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/newsscrapers/edit.html.erb
<h1>Editing Newsscraper</h1>

<%= render 'form' %>

<%= link_to 'Show', @newsscraper %> |
<%= link_to 'Back', newsscrapers_path %>

app/views/newsscrapers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome to Newsscraper</h1>
<div>
  <%= will_paginate @newsscrapers, renderer: BootstrapPagination::Rails  %>  
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Original Story</th>
      <th>Title</th>
      <th>Story Summary</th>
      <th>Story Posted At</th>
      <th>Story Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @newsscrapers.each do |newsscraper| %>
      <tr>
        <td><%= link_to "Original Story", newsscraper.title_url, :target => "_blank" %></td>
        <td><%= newsscraper.title %></td>
        <td><%= newsscraper.body %></td>
        <td><%= newsscraper.created_at.strftime("%A, %d %b %Y %l:%M %p") %></td>
        <% if newsscraper.image_url.present? %>
          <td><%= image_tag newsscraper.image_url %></td>
        <% else %>
          <td><%= image_tag 'nia.jpg' %></td>
        <% end%>
        <td><%= link_to 'Comment', newsscraper, class: "btn btn-success btn-xs" %></td>
        <% if can? :destroy, @newsscraper %>
        <td><%= link_to 'Edit', edit_newsscraper_path(newsscraper), class: "btn btn-warning btnxs" %></td>
        <% end %>
        <% if can? :destroy, @newsscraper %>
        <td><%= link_to 'Destroy', newsscraper, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @newsscrapers %>
<br>

<%= link_to 'New Newsscraper', new_newsscraper_path %>

app/views/newsscrapers/new.html.erb
<h1>New Newsscraper</h1>

<%= render 'form' %>

<%= link_to 'Back', newsscrapers_path %>

app/views/newsscrapers/show.html.erb
<p id="notice"><%= notice %></p>

<div class="pull-left padding">
  <% if @newsscraper.image_url.present? %>
    <td><%= image_tag @newsscraper.image_url %></td>
  <% else %>
    <td><%= image_tag 'nia.jpg' %></td>
  <% end%>
</div>

<p>
  <strong>View:</strong>
  <%= link_to "Original Story", @newsscraper.title_url, :target => "_blank" %>
</p>

<p>
  <strong>Headline:</strong>
  <%= @newsscraper.title %>
</p>

<p>
  <strong>Story Summary:</strong>
  <%= @newsscraper.body %>
</p>

<p>
  <strong>Posted:</strong>
  <%= time_ago_in_words(@newsscraper.created_at) %> ago
</p>


<%= link_to 'Back To Newsscraper', newsscrapers_path, class:"btn btn-info btn-xs" %>
<hr>
<%= render @newsscraper.comments %>
  <%= simple_form_for [@newsscraper, Comment.new] do|comment| %>
  <%= comment.input :body %>
  <%= comment.submit "Added Comment", class:"btn btn-danger" %>
<% end %>
<hr>
<%= link_to 'Back To Newsscraper', newsscrapers_path, class:"btn btn-info btn-xs" %>

app/views/pages/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">World News At It's Best
            <small>Award Winning Coverage</small>
        </h1>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <%= image_tag "bn.jpg", class: "img-rounded" %>
    </div>
    <div class="col-md-4">
        <h3>Latest Comments</h3>
        <% @comments.each do |comment| %>
        <ul>
            <li><%= truncate(comment.body, length: 50) %></li>
        </ul>
        <% end %> 
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Breaking News</h3>
    </div>
    <% @newsscrapers.each do |news| %>
    <div class="panel panel-default col-md-3">
        <div class="panel-heading">
            <h3 class="panel-title"><%= link_to news.title, news %></h3>
        </div>
        <div class="panel-body text-center">
            <%= image_tag news.image_url %>
        </div>
    </div>
    <% end %>
</div>
<!-- /.row -->
<hr>